name: env_myrepo
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.2.0
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.5
  - gettext=0.19.8.1
  - glib=2.58.3
  - icu=64.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.17
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - requests=2.22.0
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - urllib3=1.24.2
  - vega=2.6.0
  - vega_datasets=0.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zlib=1.2.11

