name: env_myrepo
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - vega_datasets
  - asn1crypto
  - attrs
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - entrypoints
  - idna
  - intel-openmp
  - jinja2
  - jsonschema
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - markupsafe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - openssl
  - pandas=0.25.1
  - pip
  - pycparser
  - pyopenssl
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - pytz
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - toolz
  - urllib3
  - wheel
  - xz
  - zlib

